name: Mirror and run GitLab CI


on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/IBricchi/oligopoly"
      env:
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "IBricchi"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "27890941"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
